"""Offline generation / verification of the four fixed analyzer gamut outlines.

Requires numpy and shapely only for this developer tool; neither is a runtime or
build dependency. All transforms come from analyzer_gamut_samples.cpp including
the production portable_math.inc. Faces use PQ-uniform nodes for HDR, linear for
SDR. Union of face triangles preserves nonconvex silhouettes. No radial/convex
hull approximation. Output --patch is applied with apply_patch, not a runtime
asset download. The accompanying JSON is reproducible numerical evidence.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile
import time

import numpy as np
import shapely

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "src/domain/analysis/gamut_boundary_data.inc"
MATH_SOURCES = [
    ROOT / "src/domain/analysis/portable_math.inc",
    ROOT / "src/domain/analysis/portable_color_math.inc",
]


def math_inputs():
    # Match CMake's normalized, ordered source fingerprint.
    return "".join(path.read_text().replace("\r\n", "\n") for path in MATH_SOURCES)


def envelope(exe, space, n):
    digest = hashlib.sha256(math_inputs().encode() +
                            (ROOT / "scripts/analyzer_gamut_samples.cpp").read_bytes()).hexdigest()[:16]
    cache = ROOT / ".agent/cache/analyzer-gamut"
    cache.mkdir(parents=True, exist_ok=True)
    path = cache / f"{digest}_{space}_{n}_v2.wkb"
    if path.exists():
        return shapely.from_wkb(path.read_bytes())
    raw = subprocess.check_output([str(exe), str(space), str(n)])
    faces = np.frombuffer(raw, dtype=np.float32).astype(float).reshape(6, n, n, 2)
    snap = 1e-7 if space >= 2 else 1e-5
    unions = []
    for face in faces:
        # Row strips limit peak memory while preserving all triangles.
        strips = []
        for start in range(0, n - 1, 32):
            f = face[start:min(start + 33, n)]
            tri = np.concatenate([
                np.stack([f[:-1, :-1], f[1:, :-1], f[1:, 1:]], axis=2).reshape(-1, 3, 2),
                np.stack([f[:-1, :-1], f[1:, 1:], f[:-1, 1:]], axis=2).reshape(-1, 3, 2)])
            polys = shapely.polygons(tri)
            strips.append(shapely.union_all(polys[shapely.area(polys) > 1e-18], grid_size=snap))
        unions.append(shapely.union_all(strips, grid_size=snap))
    shape = shapely.union_all(unions, grid_size=snap)
    if shape.geom_type == "MultiPolygon":
        parts = sorted(shape.geoms, key=lambda p: p.area, reverse=True)
        islands = sum(p.area for p in parts[1:])
        print(json.dumps({"space": space, "mesh": n, "numerical_island_area": islands,
                          "components": len(parts)}), flush=True)
        # RGB cube is connected and its continuous projection is connected.
        # Snap-rounded FP32 triangles can create tiny disconnected slivers.
        # Never discard a substantive disconnected region without failing.
        assert islands < snap * 10, (space, "substantive islands", islands)
        shape = parts[0]
    assert shape.geom_type == "Polygon", (space, shape.geom_type)
    holes = sum(shapely.Polygon(r).area for r in shape.interiors)
    assert holes < snap * 10, (space, "non-numerical holes", holes)
    result = shapely.Polygon(shape.exterior)
    path.write_bytes(shapely.to_wkb(result))
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mesh", type=int, default=513)
    parser.add_argument("--validation", type=Path, required=True)
    parser.add_argument("--patch", type=Path, required=True)
    args = parser.parse_args()
    assert args.mesh >= 129 and args.mesh % 2 == 1
    math_sha = hashlib.sha256(math_inputs().encode()).hexdigest()
    rows = ["// Generated by scripts/generate_analyzer_gamut.py; do not hand-edit.",
            "// D65; SDR RGB [0,1], HDR RGB [0,10000] nit; whole-volume projection.",
            f"// portable color math inputs SHA-256: {math_sha}",
            f"// Mesh {args.mesh}; float coordinates; closed contours; no runtime allocation."]
    report = {"color_math_sources_sha256": math_sha, "mesh": args.mesh, "spaces": {}}
    with tempfile.TemporaryDirectory(prefix="analyzer-gamut-generator-") as tmp:
        exe = Path(tmp) / "samples"
        subprocess.run(["/usr/bin/clang++", "-std=c++20", "-O2", "-ffp-contract=off",
                        "-I", str(ROOT / "src"), str(ROOT / "scripts/analyzer_gamut_samples.cpp"),
                        "-o", str(exe)], check=True)
        for space in range(4):
            start = time.monotonic()
            coarse = envelope(exe, space, (args.mesh + 1) // 2)
            fine = envelope(exe, space, args.mesh)
            tol = 2e-6 if space >= 2 else .0005
            simplified = shapely.simplify(fine, tol, preserve_topology=True)
            points = np.asarray(simplified.exterior.coords, dtype=np.float32)
            shape = shapely.Polygon(points.astype(float))
            convergence = float(shapely.hausdorff_distance(fine.exterior, coarse.exterior))
            error = float(shapely.hausdorff_distance(shape.exterior, fine.exterior))
            # Hard gates, not a replacement for the independent runtime tests.
            assert convergence < (8e-5 if space >= 2 else .03), (space, convergence)
            assert error < tol * 1.1
            assert shape.is_valid and len(points) < 20000
            rows.append(f"static constexpr std::array<float, 2> gamut_space_{space}[] = {{")
            for x, y in points:
                rows.append("  {" + format(float(x), ".9e") + "f, " + format(float(y), ".9e") + "f},")
            rows.append("};")
            report["spaces"][space] = {
                "vertices": len(points), "payload_bytes": int(points.nbytes),
                "mesh_boundary_hausdorff": convergence, "simplify_hausdorff": error,
                "bounds": shape.bounds, "seconds": time.monotonic() - start,
                "convex_hull_excess_area": shape.convex_hull.area - shape.area}
            print(json.dumps({"space": space, **report["spaces"][space]}), flush=True)
    generated = "\n".join(rows) + "\n"
    patch = "*** Begin Patch\n"
    if TARGET.exists():
        patch += f"*** Update File: {TARGET}\n@@\n"
        patch += "\n".join("-" + s for s in TARGET.read_text().splitlines()) + "\n"
    else:
        patch += f"*** Add File: {TARGET}\n"
    patch += "\n".join("+" + s for s in generated.splitlines()) + "\n*** End Patch\n"
    args.patch.write_text(patch)
    args.validation.write_text(json.dumps(report, indent=2) + "\n")


if __name__ == "__main__":
    main()
