# Build-time only. Keep the selected code identity stable across rebuilds and
# public exports. No dependency on Python or a network connection in app builds.
function(hdrshot_source_identity source_dir)
  set(commit "")
  set(timestamp "")
  set(modified false)
  file(STRINGS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/SourceIdentityPaths.txt" inputs)
  find_package(Git QUIET)
  set(receipt "${source_dir}/.seriousshot-export.json")
  if(EXISTS "${receipt}")
    # A public synchronization commit is NOT the source-code commit. Legacy or
    # malformed receipts remain unknown rather than inventing a newer identity.
    file(READ "${receipt}" metadata)
    string(JSON commit ERROR_VARIABLE commit_error GET "${metadata}" code_identity commit)
    string(JSON timestamp ERROR_VARIABLE time_error GET "${metadata}" code_identity timestamp)
    if(commit_error OR time_error)
      set(commit "")
      set(timestamp "")
    endif()
    set(actual_files "")
    foreach(input IN LISTS inputs)
      if(IS_DIRECTORY "${source_dir}/${input}")
        file(GLOB_RECURSE input_files LIST_DIRECTORIES false RELATIVE "${source_dir}"
          "${source_dir}/${input}/*")
        list(APPEND actual_files ${input_files})
      elseif(EXISTS "${source_dir}/${input}")
        list(APPEND actual_files "${input}")
      endif()
    endforeach()
    # Include receipt entries to catch deleted inputs as well as new/changed ones.
    string(JSON file_count ERROR_VARIABLE files_error LENGTH "${metadata}" files)
    if(files_error)
      set(commit "")
      set(timestamp "")
    elseif(file_count GREATER 0)
      math(EXPR last "${file_count} - 1")
      foreach(index RANGE 0 ${last})
        string(JSON name MEMBER "${metadata}" files ${index})
        foreach(input IN LISTS inputs)
          string(FIND "${name}" "${input}/" prefix)
          if(name STREQUAL input OR prefix EQUAL 0)
            list(APPEND actual_files "${name}")
          endif()
        endforeach()
      endforeach()
    endif()
    list(REMOVE_DUPLICATES actual_files)
    foreach(name IN LISTS actual_files)
      string(JSON expected ERROR_VARIABLE hash_error GET "${metadata}" files "${name}" sha256)
      if(hash_error OR NOT EXISTS "${source_dir}/${name}" OR IS_SYMLINK "${source_dir}/${name}")
        set(modified true)
      else()
        file(SHA256 "${source_dir}/${name}" actual)
        if(NOT actual STREQUAL expected)
          set(modified true)
        endif()
      endif()
    endforeach()
  elseif(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source_dir}"
      rev-parse --is-shallow-repository
      OUTPUT_VARIABLE shallow OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    # A shallow boundary may look like an initial commit of unchanged files.
    if(shallow STREQUAL "false")
      execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source_dir}"
        log -1 --format=%H%n%cI HEAD -- ${inputs}
        RESULT_VARIABLE result OUTPUT_VARIABLE identity
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(result EQUAL 0 AND identity MATCHES "^([0-9a-f]+)\n(.+)$")
        set(commit "${CMAKE_MATCH_1}")
        set(timestamp "${CMAKE_MATCH_2}")
      endif()
    endif()
  endif()
  if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${source_dir}"
      status --porcelain=v1 --untracked-files=all -- ${inputs}
      RESULT_VARIABLE status_result OUTPUT_VARIABLE status ERROR_QUIET)
    if(status_result EQUAL 0 AND NOT status STREQUAL "")
      set(modified true)
    endif()
  endif()
  # Values enter generated C++ literals; reject anything outside Git's formats.
  string(LENGTH "${commit}" commit_length)
  if(NOT commit MATCHES "^[0-9a-f]+$" OR
      NOT (commit_length EQUAL 40 OR commit_length EQUAL 64) OR
      NOT timestamp MATCHES "^[0-9]+-[0-9]+-[0-9]+T[0-9]+:[0-9]+:[0-9]+[+-][0-9]+:[0-9]+$")
    set(commit "")
    set(timestamp "")
  endif()
  set(HDRSHOT_SOURCE_COMMIT "${commit}" PARENT_SCOPE)
  set(HDRSHOT_SOURCE_COMMIT_TIME "${timestamp}" PARENT_SCOPE)
  set(HDRSHOT_SOURCE_MODIFIED "${modified}" PARENT_SCOPE)
endfunction()
