# Native targets only; domain/application/shared Qt remain unchanged.
add_library(hdrshot_windows_color STATIC src/platform/windows/windows_color.cpp)
target_link_libraries(hdrshot_windows_color PUBLIC hdrshot_color hdrshot_frame_cropper hdrshot_annotation_rasterizer)
target_include_directories(hdrshot_windows_color PUBLIC src)
hdrshot_enable_warnings(hdrshot_windows_color)
add_library(hdrshot_windows_capture STATIC src/platform/windows/windows_capture.cpp)
target_link_libraries(hdrshot_windows_capture PUBLIC hdrshot_windows_color PRIVATE d3d11 dxgi windowsapp shcore gdi32)
target_compile_definitions(hdrshot_windows_capture PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_capture)
add_executable(hdrshot_windows_capture_probe tools/windows_capture_probe.cpp)
target_link_libraries(hdrshot_windows_capture_probe PRIVATE hdrshot_windows_capture dwmapi)
target_compile_definitions(hdrshot_windows_capture_probe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_capture_probe)
add_library(hdrshot_windows_d3d_export STATIC src/platform/windows/windows_d3d_export.cpp)
target_link_libraries(hdrshot_windows_d3d_export PUBLIC hdrshot_windows_color PRIVATE d3d11 dxgi d3dcompiler windowsapp)
target_compile_definitions(hdrshot_windows_d3d_export PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_d3d_export)
add_library(hdrshot_windows_d3d_presenter STATIC src/platform/windows/windows_d3d_presenter.cpp)
target_link_libraries(hdrshot_windows_d3d_presenter PUBLIC hdrshot_windows_capture PRIVATE d3d11 dxgi d3dcompiler dcomp windowsapp)
target_compile_definitions(hdrshot_windows_d3d_presenter PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_d3d_presenter)
if(HDRSHOT_ENABLE_QT_HOST)
  add_library(hdrshot_windows_qt_ports STATIC src/platform/windows/windows_qt_ports.cpp)
  target_link_libraries(hdrshot_windows_qt_ports PUBLIC hdrshot_windows_capture hdrshot_input_mapper Qt6::Widgets)
  target_compile_definitions(hdrshot_windows_qt_ports PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  hdrshot_enable_warnings(hdrshot_windows_qt_ports)
  add_executable(hdrshot_windows_app WIN32 tools/windows_app.cpp)
  add_executable(hdrshot_windows_icon_writer tools/windows_icon_writer.cpp)
  target_include_directories(hdrshot_windows_icon_writer PRIVATE src)
  target_link_libraries(hdrshot_windows_icon_writer PRIVATE Qt6::Widgets)
  set(_hdrshot_windows_icon "${CMAKE_CURRENT_BINARY_DIR}/generated/SeriousShot.ico")
  add_custom_command(OUTPUT "${_hdrshot_windows_icon}"
      COMMAND ${CMAKE_COMMAND} -E env "QT_QPA_PLATFORM=offscreen"
          "PATH=$<TARGET_FILE_DIR:Qt6::Core>\;$ENV{PATH}"
          $<TARGET_FILE:hdrshot_windows_icon_writer> "${_hdrshot_windows_icon}"
      DEPENDS hdrshot_windows_icon_writer VERBATIM)
  add_custom_target(hdrshot_windows_icon DEPENDS "${_hdrshot_windows_icon}")
  add_dependencies(hdrshot_windows_app hdrshot_windows_icon)
  set(_hdrshot_windows_rc "${CMAKE_CURRENT_BINARY_DIR}/generated/windows_app.rc")
  file(WRITE "${_hdrshot_windows_rc}" "1 ICON \"${_hdrshot_windows_icon}\"\n")
  set_source_files_properties("${_hdrshot_windows_rc}" PROPERTIES OBJECT_DEPENDS "${_hdrshot_windows_icon}")
  target_sources(hdrshot_windows_app PRIVATE "${_hdrshot_windows_rc}")
  set_target_properties(hdrshot_windows_app PROPERTIES OUTPUT_NAME SeriousShot)
  target_link_libraries(hdrshot_windows_app PRIVATE hdrshot_windows_qt_ports hdrshot_windows_d3d_export
      hdrshot_windows_d3d_presenter hdrshot_capture_session hdrshot_interaction_controller
      hdrshot_multi_display_preview hdrshot_export_workflow hdrshot_ultra_hdr_codec
      hdrshot_qt_overlay_ui hdrshot_qt_settings hdrshot_qt_diagnostics hdrshot_freetype_text_rasterizer Qt6::Widgets)
  target_compile_definitions(hdrshot_windows_app PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  hdrshot_enable_warnings(hdrshot_windows_app)
  add_custom_command(TARGET hdrshot_windows_app POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:hdrshot_windows_app>/assets/fonts"
      COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/assets/fonts/NotoSansSC-VF.ttf"
          "$<TARGET_FILE_DIR:hdrshot_windows_app>/assets/fonts/NotoSansSC-VF.ttf")
  if(BUILD_TESTING)
    add_executable(hdrshot_windows_qt_ports_tests tests/windows_qt_ports_tests.cpp)
    target_link_libraries(hdrshot_windows_qt_ports_tests PRIVATE hdrshot_windows_qt_ports shell32)
    target_include_directories(hdrshot_windows_qt_ports_tests PRIVATE tests)
    target_compile_definitions(hdrshot_windows_qt_ports_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    hdrshot_enable_warnings(hdrshot_windows_qt_ports_tests)
    add_test(NAME hdrshot_windows_qt_ports_tests COMMAND hdrshot_windows_qt_ports_tests)
    set_tests_properties(hdrshot_windows_qt_ports_tests PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=windows")
  endif()
endif()
if(BUILD_TESTING)
  foreach(module IN ITEMS capture d3d_presenter)
    add_executable(hdrshot_windows_${module}_tests tests/windows_${module}_tests.cpp)
    target_link_libraries(hdrshot_windows_${module}_tests PRIVATE hdrshot_windows_${module})
    target_include_directories(hdrshot_windows_${module}_tests PRIVATE tests)
    hdrshot_enable_warnings(hdrshot_windows_${module}_tests)
    add_test(NAME hdrshot_windows_${module}_tests COMMAND hdrshot_windows_${module}_tests)
  endforeach()
  add_executable(hdrshot_windows_d3d_export_tests tests/windows_d3d_export_tests.cpp)
  target_link_libraries(hdrshot_windows_d3d_export_tests PRIVATE hdrshot_windows_d3d_export)
  target_include_directories(hdrshot_windows_d3d_export_tests PRIVATE tests)
  hdrshot_enable_warnings(hdrshot_windows_d3d_export_tests)
  add_test(NAME hdrshot_windows_d3d_export_tests COMMAND hdrshot_windows_d3d_export_tests)
  add_executable(hdrshot_windows_color_tests tests/windows_color_tests.cpp)
  target_link_libraries(hdrshot_windows_color_tests PRIVATE hdrshot_windows_color)
  target_include_directories(hdrshot_windows_color_tests PRIVATE tests)
  hdrshot_enable_warnings(hdrshot_windows_color_tests)
  add_test(NAME hdrshot_windows_color_tests COMMAND hdrshot_windows_color_tests)
endif()
