# Native targets only; domain/application/shared Qt remain unchanged.
add_library(hdrshot_windows_color STATIC src/platform/windows/windows_color.cpp)
target_link_libraries(hdrshot_windows_color PUBLIC hdrshot_color hdrshot_frame_cropper hdrshot_annotation_rasterizer)
target_include_directories(hdrshot_windows_color PUBLIC src)
hdrshot_enable_warnings(hdrshot_windows_color)
add_library(hdrshot_windows_icc STATIC src/platform/windows/windows_icc_transform.cpp)
target_include_directories(hdrshot_windows_icc PUBLIC src)
target_link_libraries(hdrshot_windows_icc PUBLIC hdrshot_windows_color PRIVATE d3d11 bcrypt)
target_compile_definitions(hdrshot_windows_icc PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_icc)
add_library(hdrshot_windows_capture STATIC src/platform/windows/windows_capture.cpp
  src/platform/windows/windows_gpu_source.cpp src/platform/windows/windows_display_mode.cpp)
target_link_libraries(hdrshot_windows_capture PUBLIC hdrshot_windows_color hdrshot_windows_icc PRIVATE d3d11 dxgi d3dcompiler windowsapp shcore gdi32)
target_compile_definitions(hdrshot_windows_capture PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_capture)
add_executable(hdrshot_windows_capture_probe tools/windows_capture_probe.cpp)
target_link_libraries(hdrshot_windows_capture_probe PRIVATE hdrshot_windows_capture dwmapi)
target_compile_definitions(hdrshot_windows_capture_probe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_capture_probe)
add_library(hdrshot_windows_d3d_export STATIC src/platform/windows/windows_d3d_export.cpp)
target_link_libraries(hdrshot_windows_d3d_export PUBLIC hdrshot_windows_color hdrshot_export_workflow PRIVATE d3d11 dxgi d3dcompiler windowsapp)
target_compile_definitions(hdrshot_windows_d3d_export PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_d3d_export)
add_library(hdrshot_windows_display_transform STATIC src/platform/windows/windows_display_transform.cpp)
target_link_libraries(hdrshot_windows_display_transform PUBLIC hdrshot_windows_capture PRIVATE d3d11)
target_include_directories(hdrshot_windows_display_transform PUBLIC src)
target_compile_definitions(hdrshot_windows_display_transform PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_display_transform)
add_library(hdrshot_windows_d3d_presenter STATIC src/platform/windows/windows_d3d_presenter.cpp)
target_link_libraries(hdrshot_windows_d3d_presenter PUBLIC hdrshot_windows_capture hdrshot_export_workflow PRIVATE d3d11 dxgi d3dcompiler dcomp windowsapp)
target_link_libraries(hdrshot_windows_d3d_presenter PUBLIC hdrshot_windows_display_transform)
target_compile_definitions(hdrshot_windows_d3d_presenter PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
hdrshot_enable_warnings(hdrshot_windows_d3d_presenter)
include(cmake/windows_analysis.cmake)
target_link_libraries(hdrshot_windows_analysis PUBLIC hdrshot_windows_display_transform)
if(HDRSHOT_ENABLE_QT_HOST)
  add_executable(hdrshot_windows_color_roundtrip_probe tools/windows_color_roundtrip_probe.cpp)
  target_link_libraries(hdrshot_windows_color_roundtrip_probe PRIVATE hdrshot_windows_d3d_presenter
      hdrshot_windows_analysis hdrshot_qt_diagnostics Qt6::Core dwmapi dcomp)
  target_compile_definitions(hdrshot_windows_color_roundtrip_probe PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  add_library(hdrshot_windows_qt_ports STATIC src/platform/windows/windows_qt_ports.cpp
      src/platform/windows/windows_window_catalog.cpp)
  target_link_libraries(hdrshot_windows_qt_ports PUBLIC hdrshot_windows_capture hdrshot_input_mapper Qt6::Widgets PRIVATE dwmapi)
  target_compile_definitions(hdrshot_windows_qt_ports PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  hdrshot_enable_warnings(hdrshot_windows_qt_ports)
  add_library(hdrshot_windows_qt_analyzer STATIC src/platform/windows/windows_qt_analyzer_controller.cpp)
  target_link_libraries(hdrshot_windows_qt_analyzer PUBLIC hdrshot_analysis_application
      hdrshot_qt_analyzer_ui hdrshot_windows_analysis hdrshot_windows_d3d_export
      hdrshot_qt_overlay_ui hdrshot_qt_diagnostics hdrshot_qt_settings)
  target_compile_definitions(hdrshot_windows_qt_analyzer PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  hdrshot_enable_warnings(hdrshot_windows_qt_analyzer)
  add_executable(hdrshot_windows_app WIN32 tools/windows_app.cpp
      src/platform/windows/windows_capture_cli.cpp)
  add_executable(hdrshot_windows_icon_writer tools/windows_icon_writer.cpp)
  target_include_directories(hdrshot_windows_icon_writer PRIVATE src)
  target_link_libraries(hdrshot_windows_icon_writer PRIVATE Qt6::Widgets)
  set(_hdrshot_windows_icon "${CMAKE_CURRENT_BINARY_DIR}/generated/SeriousShot.ico")
  add_custom_command(OUTPUT "${_hdrshot_windows_icon}"
      COMMAND ${CMAKE_COMMAND} -E env "QT_QPA_PLATFORM=offscreen"
          "PATH=$<TARGET_FILE_DIR:Qt6::Core>\;$ENV{PATH}"
          $<TARGET_FILE:hdrshot_windows_icon_writer> "${_hdrshot_windows_icon}"
      DEPENDS hdrshot_windows_icon_writer VERBATIM)
  add_custom_target(hdrshot_windows_icon DEPENDS "${_hdrshot_windows_icon}")
  add_dependencies(hdrshot_windows_app hdrshot_windows_icon)
  set(_hdrshot_windows_rc "${CMAKE_CURRENT_BINARY_DIR}/generated/windows_app.rc")
  file(WRITE "${_hdrshot_windows_rc}" "1 ICON \"${_hdrshot_windows_icon}\"\n")
  set_source_files_properties("${_hdrshot_windows_rc}" PROPERTIES OBJECT_DEPENDS "${_hdrshot_windows_icon}")
  target_sources(hdrshot_windows_app PRIVATE "${_hdrshot_windows_rc}")
  set_target_properties(hdrshot_windows_app PROPERTIES OUTPUT_NAME SeriousShot)
  target_link_libraries(hdrshot_windows_app PRIVATE hdrshot_windows_qt_ports hdrshot_windows_d3d_export
      hdrshot_windows_qt_analyzer hdrshot_headless_capture
      hdrshot_windows_d3d_presenter hdrshot_capture_session hdrshot_interaction_controller
      hdrshot_multi_display_preview hdrshot_export_workflow hdrshot_ultra_hdr_codec
      hdrshot_qt_overlay_ui hdrshot_qt_settings hdrshot_qt_diagnostics hdrshot_freetype_text_rasterizer Qt6::Widgets)
  target_compile_definitions(hdrshot_windows_app PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  hdrshot_enable_warnings(hdrshot_windows_app)
  add_custom_command(TARGET hdrshot_windows_app POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:hdrshot_windows_app>/assets/fonts"
      COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/assets/fonts/NotoSansSC-VF.ttf"
          "$<TARGET_FILE_DIR:hdrshot_windows_app>/assets/fonts/NotoSansSC-VF.ttf")
  if(BUILD_TESTING)
    add_executable(hdrshot_windows_analyzer_hwnd_smoke_tests tests/windows_analyzer_hwnd_smoke_tests.cpp)
    target_link_libraries(hdrshot_windows_analyzer_hwnd_smoke_tests PRIVATE hdrshot_windows_analysis
        hdrshot_qt_analyzer_ui hdrshot_analysis_cpu)
    target_include_directories(hdrshot_windows_analyzer_hwnd_smoke_tests PRIVATE tests)
    target_compile_definitions(hdrshot_windows_analyzer_hwnd_smoke_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    add_test(NAME hdrshot_windows_analyzer_hwnd_smoke_tests COMMAND hdrshot_windows_analyzer_hwnd_smoke_tests)
    set_tests_properties(hdrshot_windows_analyzer_hwnd_smoke_tests PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=windows" TIMEOUT 30 SKIP_RETURN_CODE 77)
    add_executable(hdrshot_windows_native_input_tests tests/windows_native_input_tests.cpp)
    target_link_libraries(hdrshot_windows_native_input_tests PRIVATE hdrshot_windows_qt_ports
        hdrshot_windows_analysis hdrshot_qt_analyzer_ui hdrshot_analysis_cpu)
    target_include_directories(hdrshot_windows_native_input_tests PRIVATE tests)
    target_compile_definitions(hdrshot_windows_native_input_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    add_test(NAME hdrshot_windows_native_input_tests COMMAND hdrshot_windows_native_input_tests)
    set_tests_properties(hdrshot_windows_native_input_tests PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=windows" TIMEOUT 45)
    add_executable(hdrshot_windows_overlay_session_tests tests/windows_overlay_session_tests.cpp)
    target_link_libraries(hdrshot_windows_overlay_session_tests PRIVATE hdrshot_windows_qt_ports
        hdrshot_windows_d3d_presenter hdrshot_qt_overlay_ui hdrshot_interaction_controller)
    target_include_directories(hdrshot_windows_overlay_session_tests PRIVATE tests)
    target_compile_definitions(hdrshot_windows_overlay_session_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    hdrshot_enable_warnings(hdrshot_windows_overlay_session_tests)
    add_test(NAME hdrshot_windows_overlay_session_tests COMMAND hdrshot_windows_overlay_session_tests)
    set_tests_properties(hdrshot_windows_overlay_session_tests PROPERTIES
        ENVIRONMENT "QT_QPA_PLATFORM=windows" TIMEOUT 45 SKIP_RETURN_CODE 77 RUN_SERIAL TRUE)
    add_test(NAME hdrshot_windows_overlay_replay_tests COMMAND hdrshot_windows_overlay_session_tests --message-replay)
    set_tests_properties(hdrshot_windows_overlay_replay_tests PROPERTIES
        ENVIRONMENT "QT_QPA_PLATFORM=windows" TIMEOUT 45 RUN_SERIAL TRUE)
    add_executable(hdrshot_windows_window_catalog_tests tests/windows_window_catalog_tests.cpp)
    target_link_libraries(hdrshot_windows_window_catalog_tests PRIVATE hdrshot_windows_qt_ports hdrshot_geometry)
    target_include_directories(hdrshot_windows_window_catalog_tests PRIVATE tests)
    target_compile_definitions(hdrshot_windows_window_catalog_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    add_test(NAME hdrshot_windows_window_catalog_tests COMMAND hdrshot_windows_window_catalog_tests)
    set_tests_properties(hdrshot_windows_window_catalog_tests PROPERTIES TIMEOUT 30)
    add_executable(hdrshot_windows_qt_ports_tests tests/windows_qt_ports_tests.cpp)
    target_link_libraries(hdrshot_windows_qt_ports_tests PRIVATE hdrshot_windows_qt_ports shell32)
    target_include_directories(hdrshot_windows_qt_ports_tests PRIVATE tests)
    target_compile_definitions(hdrshot_windows_qt_ports_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    hdrshot_enable_warnings(hdrshot_windows_qt_ports_tests)
    add_test(NAME hdrshot_windows_qt_ports_tests COMMAND hdrshot_windows_qt_ports_tests)
    set_tests_properties(hdrshot_windows_qt_ports_tests PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=windows")
  endif()
endif()
if(BUILD_TESTING)
  add_executable(hdrshot_windows_display_transform_tests tests/windows_display_transform_tests.cpp)
  target_link_libraries(hdrshot_windows_display_transform_tests PRIVATE hdrshot_windows_display_transform)
  target_include_directories(hdrshot_windows_display_transform_tests PRIVATE tests)
  target_compile_definitions(hdrshot_windows_display_transform_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  add_test(NAME hdrshot_windows_display_transform_tests COMMAND hdrshot_windows_display_transform_tests)
  set_tests_properties(hdrshot_windows_display_transform_tests PROPERTIES TIMEOUT 60)
  add_executable(hdrshot_windows_icc_transform_tests tests/windows_icc_transform_tests.cpp)
  target_link_libraries(hdrshot_windows_icc_transform_tests PRIVATE hdrshot_windows_capture)
  target_include_directories(hdrshot_windows_icc_transform_tests PRIVATE tests)
  target_compile_definitions(hdrshot_windows_icc_transform_tests PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  add_test(NAME hdrshot_windows_icc_transform_tests COMMAND hdrshot_windows_icc_transform_tests)
  set_tests_properties(hdrshot_windows_icc_transform_tests PROPERTIES TIMEOUT 60)
  add_executable(hdrshot_windows_display_mode_tests tests/windows_display_mode_tests.cpp
      src/platform/windows/windows_display_mode.cpp)
  target_include_directories(hdrshot_windows_display_mode_tests PRIVATE src tests)
  add_test(NAME hdrshot_windows_display_mode_tests COMMAND hdrshot_windows_display_mode_tests)
  add_executable(hdrshot_windows_gpu_source_tests tests/windows_gpu_source_tests.cpp)
  target_link_libraries(hdrshot_windows_gpu_source_tests PRIVATE hdrshot_windows_capture)
  target_include_directories(hdrshot_windows_gpu_source_tests PRIVATE tests)
  add_test(NAME hdrshot_windows_gpu_source_tests COMMAND hdrshot_windows_gpu_source_tests)
  set_tests_properties(hdrshot_windows_gpu_source_tests PROPERTIES TIMEOUT 30)
  foreach(module IN ITEMS capture d3d_presenter)
    add_executable(hdrshot_windows_${module}_tests tests/windows_${module}_tests.cpp)
    target_link_libraries(hdrshot_windows_${module}_tests PRIVATE hdrshot_windows_${module})
    target_include_directories(hdrshot_windows_${module}_tests PRIVATE tests)
    hdrshot_enable_warnings(hdrshot_windows_${module}_tests)
    add_test(NAME hdrshot_windows_${module}_tests COMMAND hdrshot_windows_${module}_tests)
  endforeach()
  add_executable(hdrshot_windows_d3d_export_tests tests/windows_d3d_export_tests.cpp)
  target_link_libraries(hdrshot_windows_d3d_export_tests PRIVATE hdrshot_windows_d3d_export)
  target_include_directories(hdrshot_windows_d3d_export_tests PRIVATE tests)
  hdrshot_enable_warnings(hdrshot_windows_d3d_export_tests)
  add_test(NAME hdrshot_windows_d3d_export_tests COMMAND hdrshot_windows_d3d_export_tests)
  add_executable(hdrshot_windows_color_tests tests/windows_color_tests.cpp)
  target_link_libraries(hdrshot_windows_color_tests PRIVATE hdrshot_windows_color
      hdrshot_analysis_application hdrshot_analysis_cpu)
  target_include_directories(hdrshot_windows_color_tests PRIVATE tests)
  hdrshot_enable_warnings(hdrshot_windows_color_tests)
  add_test(NAME hdrshot_windows_color_tests COMMAND hdrshot_windows_color_tests)
endif()
